---
- hosts: webserver
  remote_user: ansible
  become: yes
  become_method: sudo
  vars_files:
    - "./variables.yml"

  tasks:
  - name: Install LAMP software
    yum: 
      name: "{{ packages }}"
      state: latest
    when: ansible_facts['distribution'] == "CentOS"

  tasks:
  - name: Install LAMP software
    apt: 
      name: "{{ packages }}"
      state: latest
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Create virtualhost config directory
    file:
      path: /etc/httpd/vhost.d
      state: directory
      mode: '0755'
      owner: root

  - name: Add virtualhost config directory to http.conf
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      line: IncludeOptional vhost.d/*.conf

  - name: Create virtualhost content directories
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      owner: apache
      group: apache
      mode: '0755'
    loop:
      - /var/www/{{ sitio }}
      - /var/www/{{ sitio }}/html
      - /var/www/{{ sitio }}/cgi-bin

  - name: Create virtualhost configuration
    template: 
      src: templates/{{ sitio }}.j2
      dest: /etc/httpd/vhost.d/{{ sitio }}.conf
      owner: root
      mode: '0644'
    notify: Restart httpd

  - name: Start and enable apache
    service:
      name: "{{ packages }}"
      state: started
      enabled: yes
    when: ansible_facts['distribution'] == "CentOS"

  - name: Configure firewall
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - http
      - https

  handlers:
  - name: Restart httpd
    service:
      name: "{{ packages }}"
      state: restarted
      enabled: yes

