---
- hosts: webserver
  remote_user: ansible
  become: yes
  become_method: sudo
  vars_files:
    - "./variables.yml"

  roles:
  - role: apache-centos
    when: ansible_facts['os_family'] == "RedHat"
  - role: apache-ubuntu
    when: ansible_facts['os_family'] == "Debian"
