---
- hosts: webserver
  remote_user: ansible
  become: yes
  become_method: sudo
  vars_files:
    - "./variables.yml"

  roles:
  - role: apache-centos
    when: ansible_facts['os_family'] == "RedHat"
  - role: apache-ubuntu
    when: ansible_facts['os_family'] == "Debian"

  tasks:
  - name: Create loadbalancer configuration in CentOS
    template:
      src: ./templates/httpd.j2
      dest: /etc/httpd/vhost.d/loadbalancer.conf
      owner: root
      mode: '0664'
    when: ansible_facts['os_family'] == "RedHat"
    notify: Restart httpd

  - name: Load apache modules for proxy in Ubuntu
    apache2_module:
      name: "{{ item }}"
      state: present
    loop:
      - proxy
      - proxy_http
      - proxy_balancer
    when: ansible_facts['os_family'] == "Debian"
    notify: Restart apache2
    
  - name: Create loadbalancer configuration in Ubuntu
    template:
      src: ./templates/apache2.j2
      dest: /etc/apache2/sites-enabled/000-default.conf
      owner: root
      mode: '0664'
    when: ansible_facts['os_family'] == "Debian"
    notify: Restart apache2
