---
# tasks file for roles/apache-centos

  - name: Install apache server sofware
    apt: 
      name: apache2
      state: latest
      update_cache: yes

  - name: Start and enable apache service
    service:
      name: apache2
      state: started
      enabled: yes
  

  - name: Configure firewall
    uwf:
      rule: allow
      port: "{{ item }}"
      state: enabled
    loop:
      - 80
      - 443
