---
# tasks file for roles/apache-ubuntu

  - name: Install apache server sofware
    apt: 
      name: apache2
      state: latest
      update_cache: yes
      
  - name: Create virtualhost content directories
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      owner: root
      group: root
      mode: '0755'
    loop:
      - /var/www/html/{{ sitio }}
      - /var/www/html/{{ sitio }}/cgi-bin

  - name: Start and enable apache service
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Configure firewall
    ufw:
      rule: allow
      port: "{{ item }}"
      state: enabled
    loop:
      - 80
      - 443
      - 22
