---
# tasks file for roles/ansible-centos
  tasks:
  - name: Install Apache CentOS
    yum: 
      name: httpd
      state: latest
      
  - name: Create virtualhost config directory in CentOS
    file:
      path: /etc/httpd/vhost.d
      state: directory
      mode: '0755'
      owner: root

  - name: Add virtualhost config directory to http.conf in Centos
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      line: IncludeOptional vhost.d/*.conf
      
  - name: Create virtualhost configuration in CentOS
    template: 
      src: templates/{{ sitio }}.j2
      dest: /etc/httpd/vhost.d/{{ sitio }}.conf
      owner: root
      mode: '0644'
    notify: Restart httpd
    when: ansible_facts['distribution'] == "CentOS"
    
  - name: Start and enable apache
    service:
      name: httpd
      state: started
      enabled: yes
      
  - name: Configure firewall in CentOS
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - http
      - https
      
  handlers:
  - name: Restart Apache in CentOS
    service:
      name: httpd
      state: restarted
      enabled: yes
